name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  test:
    name: ${{ matrix.browser }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: microsoft/playwright-github-action@v1
    - run: npm install
    - run: npm run test
      env:
        BROWSER: ${{ matrix.browser }}
